<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdocNet.Parser\AdocNet.Parser.csproj" />
    <ProjectReference Include="..\..\src\AdocNet.Layout\AdocNet.Layout.csproj" />
    <ProjectReference Include="..\..\src\AdocNet.Avalonia\AdocNet.Avalonia.csproj" />
  </ItemGroup>
</Project>
