<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" Version="4.*" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdocNet.Ast\AdocNet.Ast.csproj" />
    <ProjectReference Include="..\..\src\AdocNet.Parser\AdocNet.Parser.csproj" />
    <ProjectReference Include="..\..\src\AdocNet.Emitter\AdocNet.Emitter.csproj" />
    <ProjectReference Include="..\..\src\AdocNet.Converters.Html\AdocNet.Converters.Html.csproj" />
    <ProjectReference Include="..\..\src\AdocNet.Importers.Docx\AdocNet.Importers.Docx.csproj" />
  </ItemGroup>
</Project>
