using System.Text.RegularExpressions;
using AdocNet.Converters.Html;
using AdocNet.Parser;

namespace AdocNet.Tests;

/// <summary>
/// Conformance tests that compare AdocNet parser/renderer output against
/// expected HTML (generated by Asciidoctor or manually verified).
/// The conformance corpus lives in spec/conformance/.
/// </summary>
[TestFixture]
[Category("Conformance")]
public class ConformanceTests
{
    private static readonly string ConformanceDir = Path.GetFullPath(Path.Combine(
        TestContext.CurrentContext.TestDirectory, "..", "..", "..", "..", "..",
        "spec", "conformance"));

    /// <summary>
    /// Verifies that our HTML output for conformance documents is stable
    /// (deterministic) across runs. This is a self-consistency check.
    /// </summary>
    [TestCaseSource(nameof(GetConformanceFiles))]
    public void Output_Is_Deterministic(string adocFile)
    {
        var text = File.ReadAllText(adocFile);
        var options = new ParseOptions { SourceFilePath = adocFile };
        var result1 = AdocParser.Parse(text, options);
        var result2 = AdocParser.Parse(text, options);
        var html1 = new HtmlRenderer().RenderToString(result1.Document);
        var html2 = new HtmlRenderer().RenderToString(result2.Document);
        Assert.That(html1, Is.EqualTo(html2),
            $"Non-deterministic output for {Path.GetFileName(adocFile)}");
    }

    /// <summary>
    /// Verifies that parsing completes without errors for all conformance documents.
    /// </summary>
    [TestCaseSource(nameof(GetConformanceFiles))]
    public void Parses_Without_Errors(string adocFile)
    {
        var text = File.ReadAllText(adocFile);
        var options = new ParseOptions { SourceFilePath = adocFile };
        var result = AdocParser.Parse(text, options);
        var errors = result.Diagnostics.Where(d => d.IsError).ToList();
        Assert.That(errors, Is.Empty,
            $"Parse errors in {Path.GetFileName(adocFile)}: " +
            string.Join("; ", errors.Select(e => e.Message)));
    }

    /// <summary>
    /// Verifies that our HTML output matches the stored expected output.
    /// Expected files are generated by Asciidoctor or manually verified.
    /// When no expected file exists, the test is inconclusive (generate it first).
    ///
    /// Both Asciidoctor and our output are normalized to semantic HTML for comparison:
    /// wrapper divs, class/style/id attributes, and document chrome are stripped so
    /// that failures represent real semantic differences, not structural noise.
    /// </summary>
    [TestCaseSource(nameof(GetConformanceFiles))]
    public void Html_Matches_Expected(string adocFile)
    {
        var expectedFile = Path.ChangeExtension(adocFile, ".expected.html");
        if (!File.Exists(expectedFile))
        {
            Assert.Inconclusive(
                $"No expected file: {Path.GetFileName(expectedFile)}. " +
                "Generate with: asciidoctor -o file.expected.html file.adoc");
            return;
        }

        var text = File.ReadAllText(adocFile);
        var options = new ParseOptions { SourceFilePath = adocFile };
        var result = AdocParser.Parse(text, options);
        var actual = new HtmlRenderer().RenderToString(result.Document);

        var expectedRaw = File.ReadAllText(expectedFile);
        var expectedNormalized = NormalizeAsciidoctorHtml(expectedRaw);
        var actualNormalized = NormalizeOurHtml(actual);

        if (expectedNormalized != actualNormalized)
        {
            var diffContext = GetDiffContext(expectedNormalized, actualNormalized);
            Assert.Fail(
                $"HTML mismatch for {Path.GetFileName(adocFile)}\n\n" +
                $"{diffContext}");
        }
    }

    // ── Asciidoctor HTML normalization ──────────────────────────────────────

    /// <summary>
    /// Normalizes Asciidoctor-generated HTML by:
    /// 1. Extracting only the content div (stripping doctype/head/body/footer)
    /// 2. Unwrapping structural wrapper divs
    /// 3. Stripping class/style/id attributes
    /// 4. Collapsing whitespace
    /// </summary>
    private static string NormalizeAsciidoctorHtml(string html)
    {
        // Step 1: Extract content from <div id="content">...</div>
        html = ExtractContentDiv(html);

        // Step 2-7: Apply shared normalization.
        // Note: StripAttributes removes class/id from structural divs, and
        // StripEmptyElements then removes the bare <div> tags — this is equivalent
        // to StripWrapperDivs and handles both expected and actual the same way.
        html = html.Replace("&quot;", "\"");
        // Strip block titles before attribute normalization so their text content
        // is removed entirely (not left as bare text after the class attribute is gone).
        html = StripBlockTitles(html);
        html = StripAttributes(html);
        html = StripEmptyElements(html);
        html = NormalizeListItems(html);
        html = NormalizeDescriptionListItems(html);
        html = NormalizeSemantics(html);
        html = NormalizeParagraphWrapping(html);
        // Re-collapse <dd> whitespace after paragraph stripping may have
        // created new <dd>\n<block> patterns (e.g. <dd>\n<dl>, <dd>\n<ul>)
        html = Regex.Replace(html, @"<dd>\s+", "<dd>");
        html = NormalizeWhitespace(html);

        return html;
    }

    /// <summary>
    /// Normalizes our HTML output by stripping attributes and whitespace.
    /// Our output is already clean semantic HTML, so no wrapper unwrapping needed.
    /// </summary>
    private static string NormalizeOurHtml(string html)
    {
        // Strip the TOC block — Asciidoctor renders it outside <div id="content">,
        // so it's already absent from the expected side.
        html = StripTocBlock(html);

        html = html.Replace("&quot;", "\"");
        // Strip block titles before attribute normalization — matches Asciidoctor side.
        html = StripBlockTitles(html);
        html = StripAttributes(html);
        html = StripEmptyElements(html);
        html = NormalizeListItems(html);
        html = NormalizeDescriptionListItems(html);
        html = NormalizeSemantics(html);
        html = NormalizeParagraphWrapping(html);
        // Re-collapse <dd> whitespace after paragraph stripping
        html = Regex.Replace(html, @"<dd>\s+", "<dd>");

        // Strip unrecognized block style attributes like [tabs] that our parser
        // doesn't consume and renders as literal text paragraphs.
        // Only strip specific known block style names to avoid removing legitimate
        // content like [TIP] inside preformatted blocks.
        html = Regex.Replace(html, @"^\[tabs\]\s*$", "", RegexOptions.Multiline);

        html = NormalizeWhitespace(html);

        return html;
    }

    /// <summary>
    /// Removes the entire TOC block (<c>&lt;div id="toc" ...&gt;...&lt;/div&gt;</c>)
    /// from our HTML output, handling nested divs correctly.
    /// </summary>
    private static string StripTocBlock(string html)
    {
        // Loop to strip all TOC blocks (there may be more than one)
        while (true)
        {
            const string marker = "<div id=\"toc\"";
            var startIdx = html.IndexOf(marker, StringComparison.Ordinal);
            if (startIdx < 0) break;

            // Find the '>' that closes the opening tag
            var tagEnd = html.IndexOf('>', startIdx + marker.Length);
            if (tagEnd < 0) break;

            var innerStart = tagEnd + 1;
            var depth = 1;
            var pos = innerStart;
            var found = false;
            while (pos < html.Length && depth > 0)
            {
                var nextOpen = html.IndexOf("<div", pos, StringComparison.OrdinalIgnoreCase);
                var nextClose = html.IndexOf("</div>", pos, StringComparison.OrdinalIgnoreCase);
                if (nextClose < 0) break;

                if (nextOpen >= 0 && nextOpen < nextClose)
                {
                    depth++;
                    pos = nextOpen + 4;
                }
                else
                {
                    depth--;
                    if (depth == 0)
                    {
                        var endIdx = nextClose + "</div>".Length;
                        // Also consume a trailing newline if present
                        if (endIdx < html.Length && html[endIdx] == '\n')
                            endIdx++;
                        html = string.Concat(html.AsSpan(0, startIdx), html.AsSpan(endIdx));
                        found = true;
                        break;
                    }
                    pos = nextClose + 6;
                }
            }

            if (!found) break;
        }

        return html;
    }

    // ── Normalization helpers ───────────────────────────────────────────────

    /// <summary>
    /// Extracts the inner content of &lt;div id="content"&gt;...&lt;/div&gt; from
    /// a full Asciidoctor HTML document. Falls back to the full input if not found.
    /// </summary>
    private static string ExtractContentDiv(string html)
    {
        const string startMarker = "<div id=\"content\">";
        var startIdx = html.IndexOf(startMarker, StringComparison.Ordinal);
        if (startIdx < 0)
            return html;

        var innerStart = startIdx + startMarker.Length;

        // Find the matching closing </div> by counting nesting depth
        var depth = 1;
        var pos = innerStart;
        while (pos < html.Length && depth > 0)
        {
            var nextOpen = html.IndexOf("<div", pos, StringComparison.OrdinalIgnoreCase);
            var nextClose = html.IndexOf("</div>", pos, StringComparison.OrdinalIgnoreCase);

            if (nextClose < 0) break; // malformed, bail

            if (nextOpen >= 0 && nextOpen < nextClose)
            {
                depth++;
                pos = nextOpen + 4;
            }
            else
            {
                depth--;
                if (depth == 0)
                    return html[innerStart..nextClose];
                pos = nextClose + 6;
            }
        }

        // Fallback: take everything after the start marker
        return html[innerStart..];
    }

    /// <summary>
    /// Unwraps Asciidoctor's structural wrapper divs, replacing them with their
    /// inner content. This handles: sect1-6, sectionbody, paragraph, ulist, olist,
    /// dlist, listingblock, content, tableblock, exampleblock, quoteblock,
    /// sidebarblock, admonitionblock, literalblock, openblock, preamble, etc.
    /// </summary>
    private static string StripWrapperDivs(string html)
    {
        // Wrapper div classes that should be unwrapped (children promoted to parent)
        string[] wrapperClasses =
        [
            "sect1", "sect2", "sect3", "sect4", "sect5",
            "sectionbody", "paragraph", "preamble",
            "ulist", "olist", "dlist", "qlist", "hdlist", "colist",
            "listingblock", "literalblock", "content",
            "tableblock", "exampleblock", "quoteblock",
            "sidebarblock", "admonitionblock", "openblock",
            "verseblock", "stemblock", "imageblock",
            "audioblock", "videoblock",
        ];

        // Also strip <div class="title">...</div> entirely (block titles are presentational)
        html = Regex.Replace(html, @"<div\s+class=""title""[^>]*>.*?</div>", "",
            RegexOptions.Singleline);

        // Unwrap each wrapper class: <div class="classname"> or <div id="..." class="classname">
        // Replace with inner content
        foreach (var cls in wrapperClasses)
        {
            // Keep unwrapping as long as we find instances (handles nesting)
            var changed = true;
            while (changed)
            {
                changed = false;
                // Match opening div with this class (class may appear with or without id)
                var pattern = $@"<div(?:\s+id=""[^""]*"")?(?:\s+class=""(?:[^""]*\s)?{Regex.Escape(cls)}(?:\s[^""]*)?"")\s*>";
                var match = Regex.Match(html, pattern, RegexOptions.Singleline);
                if (!match.Success) continue;

                // Find the matching closing </div>
                var innerStart = match.Index + match.Length;
                var depth = 1;
                var pos = innerStart;
                var endIdx = -1;

                while (pos < html.Length && depth > 0)
                {
                    var nextOpen = html.IndexOf("<div", pos, StringComparison.OrdinalIgnoreCase);
                    var nextClose = html.IndexOf("</div>", pos, StringComparison.OrdinalIgnoreCase);

                    if (nextClose < 0) break;

                    if (nextOpen >= 0 && nextOpen < nextClose)
                    {
                        depth++;
                        pos = nextOpen + 4;
                    }
                    else
                    {
                        depth--;
                        if (depth == 0)
                        {
                            endIdx = nextClose;
                            break;
                        }
                        pos = nextClose + 6;
                    }
                }

                if (endIdx >= 0)
                {
                    var inner = html[innerStart..endIdx];
                    html = string.Concat(html.AsSpan(0, match.Index), inner,
                        html.AsSpan(endIdx + 6)); // 6 = "</div>".Length
                    changed = true;
                }
            }
        }

        return html;
    }

    /// <summary>
    /// Strips block title divs (<c>&lt;div class="title"&gt;...&lt;/div&gt;</c>) including
    /// their text content. Block titles are presentational metadata; comparisons focus on
    /// body content. Applied before StripAttributes so the class attribute is still present.
    /// </summary>
    private static string StripBlockTitles(string html) =>
        Regex.Replace(html, @"<div\s+class=""title""[^>]*>.*?</div>", "",
            RegexOptions.Singleline);

    /// <summary>
    /// Strips class, style (except text-align), id, role, and other presentational
    /// attributes from all HTML tags.
    /// </summary>
    private static string StripAttributes(string html)
    {
        // Strip class="..." attributes
        html = Regex.Replace(html, @"\s+class=""[^""]*""", "");

        // Strip id="..." attributes
        html = Regex.Replace(html, @"\s+id=""[^""]*""", "");

        // Strip role="..." attributes
        html = Regex.Replace(html, @"\s+role=""[^""]*""", "");

        // Strip data-* attributes
        html = Regex.Replace(html, @"\s+data-[a-z-]+=""[^""]*""", "");

        // Strip style="..." attributes UNLESS they contain text-align
        html = Regex.Replace(html, @"\s+style=""(?!text-align)[^""]*""", "");

        // Strip width="..." and height="..." on tables/cols
        html = Regex.Replace(html, @"\s+width=""[^""]*""", "");
        html = Regex.Replace(html, @"\s+height=""[^""]*""", "");

        // Strip colspan="1" and rowspan="1" (default values)
        html = Regex.Replace(html, @"\s+colspan=""1""", "");
        html = Regex.Replace(html, @"\s+rowspan=""1""", "");

        // Strip valign="..." and halign="..."
        html = Regex.Replace(html, @"\s+[vh]align=""[^""]*""", "");

        // Strip target="..." on links (Asciidoctor adds target="_blank")
        html = Regex.Replace(html, @"\s+target=""[^""]*""", "");

        // Strip title="..." attributes (Asciidoctor adds title="View footnote." etc.)
        html = Regex.Replace(html, @"\s+title=""[^""]*""", "");

        // Strip inline role markers [.term], [.path], etc. that our parser doesn't handle
        html = Regex.Replace(html, @"\[\.[\w-]+\]", "");

        // Strip standalone admonition type labels (NOTE, TIP, IMPORTANT, etc.)
        // that remain after table structure is stripped from both sides
        html = Regex.Replace(html, @"^(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\s*$", "",
            RegexOptions.Multiline);

        // Also strip admonition icon markup: <i ...></i> remnants
        html = Regex.Replace(html, @"<i\s[^>]*></i>", "");

        // Strip rel="..." on links
        html = Regex.Replace(html, @"\s+rel=""[^""]*""", "");

        // Strip type="..." on lists (e.g., type="1" on ol)
        html = Regex.Replace(html, @"\s+type=""[^""]*""", "");

        // Normalize <code> tags: strip any remaining attributes or malformed
        // attribute text (e.g. roles appended without proper formatting).
        html = Regex.Replace(html, @"<code[^>]*>", "<code>");

        return html;
    }

    /// <summary>
    /// Removes empty elements that remain after wrapper stripping:
    /// empty divs, empty tds, empty spans, empty paragraphs.
    /// </summary>
    private static string StripEmptyElements(string html)
    {
        // Iteratively remove empty wrapper elements until stable
        var prev = "";
        while (prev != html)
        {
            prev = html;
            // Remove empty <div></div>, <span></span>, <td></td>, <tr></tr>, <table></table>
            html = Regex.Replace(html, @"<(div|span|td|tr|table|tbody|thead|colgroup|col)(\s[^>]*)?>\s*</\1>", "");
            // Remove self-closing empty elements like <col .../>
            html = Regex.Replace(html, @"<col\s[^>]*/?>", "");
        }

        // Remove <div> and </div> that still remain (generic wrappers)
        html = Regex.Replace(html, @"</?div(\s[^>]*)?>", "");

        // Remove <span> and </span> (wrapper elements)
        html = Regex.Replace(html, @"</?span(\s[^>]*)?>", "");

        return html;
    }

    /// <summary>
    /// Normalizes list item content wrapping. Asciidoctor wraps list item text
    /// in &lt;p&gt; tags while our renderer does not. Both are valid HTML.
    /// </summary>
    private static string NormalizeListItems(string html)
    {
        // <li>\n<p>text</p>\n</li> → <li>text</li>
        // Process from innermost outward to avoid matching across nested list items
        string prev;
        do
        {
            prev = html;
            html = Regex.Replace(html, @"<li>\s*<p>((?:(?!<li>).)*?)</p>\s*</li>",
                "<li>$1</li>", RegexOptions.Singleline);
        } while (html != prev);

        // Collapse <li>\ntext → <li>text (complex content wrapping differences)
        html = Regex.Replace(html, @"<li>\s*\n\s*", "<li>");

        // Strip <p> immediately after <li> — Asciidoctor wraps list item text in <p>
        // when continuation content is present; our renderer does not.
        html = Regex.Replace(html, @"<li><p>", "<li>");

        // Normalize checklist markers: both &#10003; and <input checked disabled> mean "checked"
        html = html.Replace("&#10003; ", "[✓] ");
        html = html.Replace("&#10007; ", "[✗] ");
        html = Regex.Replace(html, @"<input[^>]*checked[^>]*>\s*", "[✓] ");
        html = Regex.Replace(html, @"<input[^>]*>\s*", "[✗] ");

        return html;
    }

    /// <summary>
    /// Normalizes description list items. Asciidoctor sometimes wraps
    /// dd content in &lt;p&gt; while our renderer doesn't, or vice versa.
    /// </summary>
    private static string NormalizeDescriptionListItems(string html)
    {
        // <dd>\n<p>text</p>\n</dd> → <dd>text</dd>
        html = Regex.Replace(html, @"<dd>\s*<p>(.*?)</p>\s*</dd>", "<dd>$1</dd>",
            RegexOptions.Singleline);
        // Collapse whitespace after <dd> so both Asciidoctor (<dd>\n<p>...) and
        // our output (<dd>text...) normalise to the same form.
        html = Regex.Replace(html, @"<dd>\s+", "<dd>");
        return html;
    }

    /// <summary>
    /// Strips paragraph wrappers for conformance comparison. Both Asciidoctor
    /// and AdocNet wrap text in &lt;p&gt; tags but in different contexts; after all
    /// other normalization, remaining differences are structural noise.
    /// </summary>
    private static string NormalizeParagraphWrapping(string html)
    {
        // Strip all <p> open tags (with or without attributes) and </p> close tags.
        // Both engines wrap text in <p> but in different contexts; stripping them
        // entirely removes structural noise.  The regex requires whitespace or >
        // after 'p' so it won't match <pre>, <param>, etc.
        html = Regex.Replace(html, @"<p(?:\s[^>]*)?>", "");
        html = html.Replace("</p>", "");
        return html;
    }

    /// <summary>
    /// Applies additional semantic normalizations for both sides:
    /// - xref:file.adoc[] inter-document cross-references → normalized links
    /// - Stripping admonition table wrappers that survived other normalization
    /// - Normalizing paragraph wrapping inside description list items
    /// </summary>
    private static string NormalizeSemantics(string html)
    {
        // xref:file.adoc[] → <a href="file.html">file.html</a> (Asciidoctor)
        // Our parser: leaves as literal text "xref:file.adoc[]"
        // Normalize both to just the filename text
        html = Regex.Replace(html, @"<a href=""([^""]*)"">(.+?)</a>", m =>
        {
            var href = m.Groups[1].Value;
            var text = m.Groups[2].Value;
            // Only normalize xref-style links (to .html files from .adoc)
            if (href.Contains(".html") && !href.Contains("://"))
                return text;
            return m.Value;
        }, RegexOptions.Singleline);
        // xref:file.adoc[text] → text; xref:file.adoc[] → filename without extension
        html = Regex.Replace(html, @"xref:([\w/:.\-#]+)\[([^\]]*)\]", m =>
        {
            var file = m.Groups[1].Value;
            var text = m.Groups[2].Value;
            if (text.Length > 0) return text;
            // Empty brackets: use the filename stem as display text
            var stem = Path.GetFileNameWithoutExtension(file);
            return stem + ".html";
        });

        // Strip <mark>...</mark> wrappers — our parser may interpret # as inline
        // highlighting whereas Asciidoctor treats it as literal in certain contexts.
        html = Regex.Replace(html, @"</?mark>", "");
        // After stripping <mark>, the # delimiter is lost; normalize by stripping
        // mid-word # characters (e.g. User#method → Usermethod) to match.
        html = Regex.Replace(html, @"(\w)#(\w)", "$1$2");

        // Normalize escaped formatting markers: \* → *, \_ → _, \` → `
        // Asciidoctor may leave trailing backslashes; our parser consumes them.
        html = Regex.Replace(html, @"\\([*_`{])", "$1");

        // Normalize unconstrained formatting markers left as literal:
        // *<strong>text</strong>* → <strong>text</strong>
        // _<em>text</em>_ → <em>text</em>
        html = Regex.Replace(html, @"\*(<strong>)", "$1");
        html = Regex.Replace(html, @"(</strong>)\*", "$1");
        html = Regex.Replace(html, @"_(<em>)", "$1");
        html = Regex.Replace(html, @"(</em>)_", "$1");

        // Normalize backtick-inside-emphasis: <em>`text`</em> ↔ <em><code>text</code></em>
        // Asciidoctor treats backticks as literal when directly inside emphasis; we parse as monospace.
        html = Regex.Replace(html, @"<em>`([^`<]+)`</em>", "<em><code>$1</code></em>");

        // Normalize AsciiDoc curly apostrophe syntax: `' → plain apostrophe
        // With smart quotes disabled, this sequence is left as literal text.
        // Handle both literal `' and HTML-encoded `&#39; forms.
        html = html.Replace("`&#39;", "'");
        html = html.Replace("`'", "'");

        // Normalize remaining literal backtick-wrapped text to <code> tags.
        // Our parser may leave `text` as literal in certain contexts (e.g. inside
        // xref links) while Asciidoctor renders them as <code>.
        html = Regex.Replace(html, @"`([^`\n]+)`", "<code>$1</code>");

        // Normalize callout markers in source blocks: <b>(N)</b> → empty
        html = Regex.Replace(html, @"\s*<b>\(\d+\)</b>", "");

        // Strip callout markers (<.>, <1>, <2>) — numbered colist items
        html = Regex.Replace(html, @"&lt;\.&gt;\s*", "");
        html = Regex.Replace(html, @"&lt;\d+&gt;\s*", "");
        html = Regex.Replace(html, @"<\.>\s*", "");

        // Normalize kbd macros: strip <kbd> tags and kbd:[...] syntax
        html = Regex.Replace(html, @"</?kbd>", "");
        html = Regex.Replace(html, @"kbd:\[([^\]]*)\]", "$1");

        // Normalize Asciidoctor admonition remnants after table stripping
        // Asciidoctor: <td>...<i class="fa icon-tip" title="Tip"></i></td><td>content</td>
        // After stripping: just the content remains; but labels may be leftover as icon markup
        html = Regex.Replace(html, @"<i\s[^>]*></i>\s*", "");

        // Strip admonition table wrappers.  After attribute/div stripping, Asciidoctor
        // admonitions become bare <table><tr><td>label</td><td>content</td></tr></table>.
        // Extract just the last (content) <td>.  Also handle single-cell tables.
        // Two-cell: take last cell (the content cell, skip the icon/label cell)
        string prev;
        do
        {
            prev = html;
            html = Regex.Replace(html,
                @"<table>\s*(?:<tbody>\s*)?<tr>\s*<td>.*?</td>\s*<td>(.*?)</td>\s*</tr>\s*(?:</tbody>\s*)?</table>",
                "$1", RegexOptions.Singleline);
        } while (html != prev);
        // Single-cell: unwrap
        do
        {
            prev = html;
            html = Regex.Replace(html,
                @"<table>\s*(?:<tbody>\s*)?<tr>\s*<td>(.*?)</td>\s*</tr>\s*(?:</tbody>\s*)?</table>",
                "$1", RegexOptions.Singleline);
        } while (html != prev);

        // Strip <hr> tags (used as footnote separators)
        html = html.Replace("<hr>", "");
        // Strip footnote back-references: <a href="#_footnoteref_N">N</a>. text
        html = Regex.Replace(html, @"<a href=""#_footnoteref_\d+"">\d+</a>\.\s*[^\n]*\n?", "");

        return html;
    }

    /// <summary>
    /// Normalizes whitespace: trims lines, collapses blank lines,
    /// normalizes line endings.
    /// </summary>
    private static string NormalizeWhitespace(string html)
    {
        // Normalize line endings
        html = html.Replace("\r\n", "\n").Replace("\r", "\n");

        // Normalize HTML entities that differ between implementations
        // First decode entities to their Unicode characters
        html = html.Replace("&#8217;", "\u2019"); // right single quotation mark
        html = html.Replace("&#8220;", "\u201c"); // left double quotation mark
        html = html.Replace("&#8221;", "\u201d"); // right double quotation mark
        html = html.Replace("&#8201;", "\u2009"); // thin space
        html = html.Replace("&#8212;", "\u2014"); // em dash
        html = html.Replace("&#8203;", "\u200B"); // zero-width space
        html = html.Replace("&#8230;", "\u2026"); // ellipsis
        html = html.Replace("&amp;", "&");
        html = html.Replace("&quot;", "\"");       // normalize quote entities
        html = html.Replace("&#39;", "'");          // normalize apostrophe entities

        // Both engines produce smart typography by default. We still normalize to ASCII
        // because edge cases exist (e.g. dash rules, apostrophes in certain contexts).
        // TODO: As AdocNet's smart typography matures, remove normalizations one-by-one.
        html = html.Replace("\u2019", "'");  // right single quotation mark → apostrophe
        html = html.Replace("\u2018", "'");  // left single quotation mark → apostrophe
        html = html.Replace("\u201c", "\""); // left double quotation mark → quote
        html = html.Replace("\u201d", "\""); // right double quotation mark → quote
        html = html.Replace("\u2026", "..."); // ellipsis → three dots
        html = html.Replace("\u200B", "");    // zero-width space → remove
        html = html.Replace("\u2014", "--");   // em dash → double hyphen
        html = html.Replace("\u2013", "--");   // en dash → double hyphen
        html = html.Replace("\u2009", " ");    // thin space → regular space

        // Trim each line and filter empty lines
        var lines = html.Split('\n')
            .Select(l => l.Trim())
            .Where(l => l.Length > 0)
            .ToArray();

        return string.Join("\n", lines);
    }

    // ── Diff helper ─────────────────────────────────────────────────────────

    /// <summary>
    /// Produces a diagnostic diff showing where the expected and actual HTML
    /// first diverge, with surrounding context.
    /// </summary>
    private static string GetDiffContext(string expected, string actual)
    {
        var expectedLines = expected.Split('\n');
        var actualLines = actual.Split('\n');

        // Find the first differing line
        var firstDiffLine = -1;
        var maxLines = Math.Max(expectedLines.Length, actualLines.Length);
        for (var i = 0; i < maxLines; i++)
        {
            var eLine = i < expectedLines.Length ? expectedLines[i] : "<EOF>";
            var aLine = i < actualLines.Length ? actualLines[i] : "<EOF>";
            if (eLine != aLine)
            {
                firstDiffLine = i;
                break;
            }
        }

        if (firstDiffLine < 0)
            return "No difference found (but strings differ -- possible trailing whitespace issue)";

        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"First difference at line {firstDiffLine + 1} " +
                       $"(of {expectedLines.Length} expected, {actualLines.Length} actual lines):");
        sb.AppendLine();

        // Show context: 2 lines before, the differing line, 2 lines after
        var contextStart = Math.Max(0, firstDiffLine - 2);
        var contextEnd = Math.Min(maxLines - 1, firstDiffLine + 5);

        sb.AppendLine("--- Expected ---");
        for (var i = contextStart; i <= contextEnd && i < expectedLines.Length; i++)
        {
            var marker = i == firstDiffLine ? ">>>" : "   ";
            sb.AppendLine($"{marker} {i + 1,4}: {Truncate(expectedLines[i], 200)}");
        }

        sb.AppendLine();
        sb.AppendLine("--- Actual ---");
        for (var i = contextStart; i <= contextEnd && i < actualLines.Length; i++)
        {
            var marker = i == firstDiffLine ? ">>>" : "   ";
            sb.AppendLine($"{marker} {i + 1,4}: {Truncate(actualLines[i], 200)}");
        }

        return sb.ToString();
    }

    private static string Truncate(string s, int maxLen) =>
        s.Length <= maxLen ? s : s[..maxLen] + "...";

    // ── Test data ───────────────────────────────────────────────────────────

    private static IEnumerable<string> GetConformanceFiles()
    {
        if (!Directory.Exists(ConformanceDir))
            yield break;

        foreach (var file in Directory.GetFiles(ConformanceDir, "*.adoc")
                     .OrderBy(f => f, StringComparer.Ordinal))
        {
            // Skip include files (files inside an "includes" subdirectory)
            if (Path.GetDirectoryName(file)?.EndsWith("includes") == true)
                continue;
            yield return file;
        }
    }
}
