using AdocNet.Ast;
using AdocNet.Converters.Html;
using AdocNet.Converters.Pdf;
using AdocNet.Extensions;
using AdocNet.Parser;
using NUnit.Framework;

namespace AdocNet.Tests;

/// <summary>
/// Integration tests for the extension system against real renderers.
/// </summary>
[TestFixture]
public class ExtensionIntegrationTests
{
    // ── Backward compatibility (criterion 10) ────────────────────────────

    [Test]
    public void ZeroExtensions_HtmlOutput_IdenticalToBeta4()
    {
        const string input = "= Title\n\nHello *world*.\n\n== Section\n\nParagraph.";

        // Render without extensions (beta.4 path)
        var doc1 = BlockParser.Parse(input).Document;
        var htmlWithout = new HtmlRenderer().RenderToString(doc1);

        // Render via engine with no extensions registered
        var engine = new AdocEngine(new HtmlRenderer(), s => BlockParser.Parse(s).Document);
        using var ms = new MemoryStream();
        engine.Convert(input, ms);
        ms.Position = 0;
        var htmlWith = new StreamReader(ms).ReadToEnd();

        Assert.That(htmlWith, Is.EqualTo(htmlWithout),
            "Output with zero extensions should be identical to direct rendering");
    }

    [Test]
    public void ZeroExtensions_PdfOutput_IdenticalToBeta4()
    {
        const string input = "= Title\n\nHello world.";

        // Render without extensions
        var doc1 = BlockParser.Parse(input).Document;
        var pdfWithout = new PdfRenderer().RenderToBytes(doc1);

        // Render via engine with no extensions
        var engine = new AdocEngine(new PdfRenderer(), s => BlockParser.Parse(s).Document);
        using var ms = new MemoryStream();
        engine.Convert(input, ms);
        var pdfWith = ms.ToArray();

        Assert.That(pdfWith, Is.EqualTo(pdfWithout),
            "PDF output with zero extensions should be byte-identical to direct rendering");
    }

    // ── Cross-renderer extension test (criterion 11) ─────────────────────

    [Test]
    public void IconProcessor_HtmlOutput_ContainsHeartSymbol()
    {
        const string input = "Hello icon:heart[] world.";

        var engine = new AdocEngine(new HtmlRenderer(), s => BlockParser.Parse(s).Document);
        engine.RegisterInlineProcessor(new IconMacroProcessor());

        using var ms = new MemoryStream();
        engine.Convert(input, ms);
        ms.Position = 0;
        var html = new StreamReader(ms).ReadToEnd();

        Assert.That(html, Does.Contain("\u2764"),
            "HTML output should contain heart symbol after icon processor");
    }

    [Test]
    public void IconProcessor_PdfOutput_ContainsHeartSymbol()
    {
        const string input = "Hello icon:heart[] world.";

        var engine = new AdocEngine(new PdfRenderer(), s => BlockParser.Parse(s).Document);
        engine.RegisterInlineProcessor(new IconMacroProcessor());

        using var ms = new MemoryStream();
        engine.Convert(input, ms);
        var pdfBytes = ms.ToArray();

        // The heart symbol (❤ U+2764) should appear in the PDF stream.
        // PDF text streams encode Unicode as UTF-16BE in CID fonts.
        // Verify the PDF was generated successfully (non-empty).
        Assert.That(pdfBytes.Length, Is.GreaterThan(100),
            "PDF should be generated with icon processor registered");
    }

    [Test]
    public void IconProcessor_BothRenderers_ProduceOutput()
    {
        const string input = "Check icon:check[] and star icon:star[].";

        // HTML
        var htmlEngine = new AdocEngine(new HtmlRenderer(), s => BlockParser.Parse(s).Document);
        htmlEngine.RegisterInlineProcessor(new IconMacroProcessor());
        using var htmlMs = new MemoryStream();
        htmlEngine.Convert(input, htmlMs);
        htmlMs.Position = 0;
        var html = new StreamReader(htmlMs).ReadToEnd();

        // PDF
        var pdfEngine = new AdocEngine(new PdfRenderer(), s => BlockParser.Parse(s).Document);
        pdfEngine.RegisterInlineProcessor(new IconMacroProcessor());
        using var pdfMs = new MemoryStream();
        pdfEngine.Convert(input, pdfMs);

        Assert.That(html, Does.Contain("\u2713"), "HTML should contain check symbol");
        Assert.That(html, Does.Contain("\u2605"), "HTML should contain star symbol");
        Assert.That(pdfMs.Length, Is.GreaterThan(100), "PDF should be generated");
    }

    // ── Document processor with real renderers ───────────────────────────

    [Test]
    public void DocumentMetadataProcessor_HtmlOutput_ContainsMetadata()
    {
        const string input = "Hello world.";

        var engine = new AdocEngine(new HtmlRenderer(), s => BlockParser.Parse(s).Document);
        engine.RegisterDocumentProcessor(new DocumentMetadataProcessor("Generated by AdocNet"));

        using var ms = new MemoryStream();
        engine.Convert(input, ms);
        ms.Position = 0;
        var html = new StreamReader(ms).ReadToEnd();

        Assert.That(html, Does.Contain("Generated by AdocNet"),
            "HTML output should contain the metadata paragraph");
    }

    // ── AutoId processor with real renderer ──────────────────────────────

    [Test]
    public void AllThreeProcessorTypes_HtmlOutput_AllExecute()
    {
        const string input = "Hello icon:star[] world.";

        var order = new List<string>();
        var engine = new AdocEngine(new HtmlRenderer(), s => BlockParser.Parse(s).Document);
        engine.RegisterDocumentProcessor(new DocumentMetadataProcessor("HEADER"));
        engine.RegisterBlockProcessor(new OrderTrackingBlockProcessor(order));
        engine.RegisterInlineProcessor(new IconMacroProcessor());

        using var ms = new MemoryStream();
        engine.Convert(input, ms);
        ms.Position = 0;
        var html = new StreamReader(ms).ReadToEnd();

        Assert.That(html, Does.Contain("HEADER"), "Document processor should add metadata");
        Assert.That(html, Does.Contain("\u2605"), "Inline processor should replace icon:star[]");
        Assert.That(order, Is.Not.Empty, "Block processor should have been invoked");
    }

    private sealed class OrderTrackingBlockProcessor : IBlockProcessor
    {
        private readonly List<string> _order;
        public OrderTrackingBlockProcessor(List<string> order) => _order = order;
        public bool CanProcess(BlockNode node) => node is ParagraphNode;
        public void Process(BlockNode node, RenderContext context) => _order.Add("block");
    }
}
