<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework />
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <RootNamespace>AdocNet.Parser</RootNamespace>
    <Description>AsciiDoc parser for the Adoc.Net library. The AdocParser class is the primary entry point.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AdocNet.Tests" />
    <InternalsVisibleTo Include="AdocNet.Converters.Html" />
    <InternalsVisibleTo Include="AdocNet.Converters.DocBook" />
    <InternalsVisibleTo Include="AdocNet.Converters.Man" />
    <InternalsVisibleTo Include="AdocNet.Converters.Revealjs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdocNet.Core\AdocNet.Core.csproj" />
    <ProjectReference Include="..\AdocNet.Ast\AdocNet.Ast.csproj" />
  </ItemGroup>
</Project>
