<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>test.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AdocNet.Core\AdocNet.Core.csproj" />
  </ItemGroup>
</Project>
